ClinicApp/ClinicApp.Presentation/Controllers/DoctorController.cs
namespace ClinicApp.Presentation.Controllers;

using Microsoft.AspNetCore.Mvc;
using ClinicApp.Infrastructure.Repositories.Doctor.Base;

public class DoctorController : Controller
{
    private readonly IDoctorRepository doctorRepository;
    public DoctorController(IDoctorRepository doctorRepository)
    {
        this.doctorRepository = doctorRepository;
    }

    [HttpGet]
    public async Task<IActionResult> ShowDoctorByMedicalDepartment(int medicalDepartment)
    {
        var doctors = await doctorRepository.GetDoctorsByMedicalDepartment(medicalDepartment);
        return View(model: doctors);
    }

    [HttpGet]
    public async Task<IActionResult> ShowAllDoctors()
    {
        var doctors = await doctorRepository.GetAllDoctors();
        return View(model: doctors);
    
    }
}

ClinicApp/ClinicApp.Presentation/Controllers/HomeController.cs
namespace ClinicApp.Presentation.Controllers;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.DataProtection;
using ClinicApp.Infrastructure.Repositories.MedicalEmployee.Base;
using ClinicApp.Core.DTO.MedicalEmployee;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;

public class HomeController : Controller
{
    private readonly IMedicalEmployeeRepository medicalEmployeeRepository;
    private readonly IDataProtector dataProtector;
    public HomeController(IMedicalEmployeeRepository medicalEmployeeRepository, IDataProtectionProvider dataProtectionProvider)
    {
        this.medicalEmployeeRepository = medicalEmployeeRepository;
        this.dataProtector = dataProtectionProvider.CreateProtector("IdentityProtection");
    }

    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }

    public async Task<IActionResult> Logout()
    {
        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        return RedirectToAction("Index", "Home");
    }

    public IActionResult Login()
    {
        return View(model: new MedicalEmployeeLogintDTO());
    }

    [HttpPost]
    public async Task<IActionResult> Login(MedicalEmployeeLogintDTO medicalEmployeeLogingDTO)
    {
        if (ModelState.IsValid == false) { return View(); }
        var result = await medicalEmployeeRepository.LoginAsync(medicalEmployeeLogingDTO.Email, medicalEmployeeLogingDTO.Password);
        if (result is null) { return RedirectToAction("Index", "Home"); }
        var claims = new List<Claim>() {
            new Claim(ClaimTypes.Role, result.Role.ToString()),
            new Claim("MedicalEmployeeId", result.Id.ToString())
        };
        var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));
        return RedirectToAction("Index", "Home");
    }
}

ClinicApp/ClinicApp.Presentation/Controllers/PatientController.cs
namespace ClinicApp.Presentation.Controllers;

using Newtonsoft.Json;
using ClinicApp.Core.ViewModels;
using Microsoft.AspNetCore.Mvc;
using ClinicApp.Core.Models.ClinicEntities.Doctor;
using ClinicApp.Infrastructure.Repositories.Doctor.Base;
using ClinicApp.Infrastructure.Repositories.Patient.Base;

public class PatientController : Controller
{
    private readonly IPatientRepository patientRepository;
    private readonly IDoctorRepository doctorRepository;
    public PatientController(IPatientRepository patientRepository, IDoctorRepository doctorRepository)
    {
        this.patientRepository = patientRepository;
        this.doctorRepository = doctorRepository;
    }

    [HttpPost]
    public IActionResult CreatePatient([FromForm(Name = "doctor")] string doctorJson)
    {
        var doctorTO = JsonConvert.DeserializeObject<Doctor>(doctorJson);
        var viewModelDoctorPatient = new ViewModelDoctorPatient() { doctor = doctorTO ?? new Doctor() };
        return View(model: viewModelDoctorPatient);
    }

    [HttpGet]
    public async Task<IActionResult> ShowAllPatients()
    {
        var patients = await patientRepository.GetAllPatients();
        return View(model: patients);
    }

    [HttpGet]
    public async Task<IActionResult> ShowPatientsByDoctor([FromQuery] string doctorFIN)
    {
        var patients = await patientRepository.GetPatientsByDoctor(doctorFIN);
        var doctor = await doctorRepository.GetDoctorByFIN(doctorFIN);
        var viewModelPatientsByDoctor = new ViewModelPatientsByDoctor();
        viewModelPatientsByDoctor.doctor = doctor;
        viewModelPatientsByDoctor.patients = patients;
        return View(model: viewModelPatientsByDoctor);
    }
}

ClinicApp/ClinicApp.Presentation/Controllers/RegistrationController.cs
namespace ClinicApp.Presentation.Controllers;

using Microsoft.AspNetCore.Mvc;
using ClinicApp.Core.ViewModels;
using ClinicApp.Core.Models.ClinicEntities.Patient;
using ClinicApp.Infrastructure.Repositories.Doctor.Base;
using ClinicApp.Infrastructure.Repositories.Patient.Base;
using ClinicApp.Core.DTO.MedicalEmployee;
using ClinicApp.Core.Models.ClinicEntities.MedicalEmployee;
using ClinicApp.Infrastructure.Repositories.MedicalEmployee.Base;
using ClinicApp.Core.DTO.Doctor;
using ClinicApp.Core.DTO.Patient;

public class RegistrationController : Controller
{
    private readonly IPatientRepository patientRepository;
    private readonly IDoctorRepository doctorRepository;
    private readonly IMedicalEmployeeRepository medicalEmployeeRepository;
    public RegistrationController(IPatientRepository patientRepository, IDoctorRepository doctorRepository, IMedicalEmployeeRepository medicalEmployeeRepository)
    {
        this.patientRepository = patientRepository;
        this.doctorRepository = doctorRepository;
        this.medicalEmployeeRepository = medicalEmployeeRepository;
    }

    [HttpGet]
    public IActionResult RegistrationPatient()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> RegistrationPatient([FromForm] DoctorDTO doctor, [FromForm] PatientDTO patient)
    {
        await patientRepository.AddPatient(new Patient
        {
            FIN = patient.FIN,
            Firstname = patient.Firstname,
            Lastname = patient.Lastname,
            Email = patient.Email
        });
        var patientId = (await patientRepository.GetPatientByFIN(patient.FIN)).Id;
        var doctorId = (await doctorRepository.GetDoctorByFIN(doctor.FIN)).Id;
        await doctorRepository.AddPatientToDoctor(doctorId: doctorId, patientId: patientId);
        string url = $@"/Registration/Receipt?doctorFIN={doctor.FIN}&patientFIN={patient.FIN}";
        string script = $@"<script> window.open('{url}', '_blank'); window.location.href = '/Home/Index'; </script>";
        return Content(script, "text/html");
    }

    [HttpGet]
    public IActionResult RegistrationEmployee()
    {
        return View(model: new MedicalEmployeeRegistrationDTO());
    }

    [HttpPost]
    public async Task<IActionResult> RegistrationEmployee([FromForm] MedicalEmployeeRegistrationDTO medicalemployeeDTO)
    {
        await medicalEmployeeRepository.AddEmployee(new MedicalEmployee
        {
            Email = medicalemployeeDTO.Email,
            Firstname = medicalemployeeDTO.Firstname,
            Lastname = medicalemployeeDTO.Lastname,
            Password = medicalemployeeDTO.Password,
            Role = Core.Models.ManageTools.AccessRoles.MedicalReceptionist
        });
        string url = $@"/Registration/SuccessfulRegistrationMessage?medicalemployeeEmail={medicalemployeeDTO.Email}";
        string script = $@"<script> window.open('{url}', '_blank'); window.location.href = '/Home/Index'; </script>";
        return Content(script, "text/html");
    }

    [HttpGet]
    public async Task<IActionResult> SuccessfulRegistrationMessage(string medicalemployeeEmail)
    {
        var medicalemployee = await medicalEmployeeRepository.GetEmployeeByEmail(medicalemployeeEmail);
        return View(model: medicalemployee);
    }

    [HttpGet]
    public async Task<IActionResult> Receipt(string doctorFIN, string patientFIN)
    {
        var veiwModel = new ViewModelDoctorPatient();
        veiwModel.doctor = await doctorRepository.GetDoctorByFIN(doctorFIN);
        veiwModel.patient = await patientRepository.GetPatientByFIN(patientFIN);
        return View(veiwModel);
    }
}

ClinicApp/ClinicApp.Presentation/Views/Doctor/ShowAllDoctors.cshtml
@model IEnumerable<Doctor>;
@{
    ViewData["Title"] = "Doctor List";
}

<h2>Doctors</h2>
<div>
    @foreach (var doctor in Model)
    {
        <form method="get" asp-controller="Patient" asp-action="ShowPatientsByDoctor">
            <input type="hidden" name="doctorFIN" value="@doctor.FIN" />
            <button type="submit" class="nav-link text-dark"
                style="border: none; background-color: transparent; cursor: pointer;">Show Patients</button>
            <div class="card mb-4">
                <div class="card-header">
                    @doctor.Firstname
                </div>
                <div class="card-header">
                    @doctor.Lastname
                </div>
                <div class="card-header">
                    @doctor.MedicalDepartment
                </div>
            </div>
        </form>
    }
</div>

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

ClinicApp/ClinicApp.Presentation/Views/Doctor/ShowDoctorByMedicalDepartment.cshtml
@model IEnumerable<Doctor>;
@{
    ViewData["Title"] = "Registration to doctor";
}


<h2>Doctors</h2>
<div>
    @foreach (var doctor in Model)
    {
        <form method="post" asp-controller="Patient" asp-action="CreatePatient">
            <input type="hidden" name="doctor" value="@JsonConvert.SerializeObject(doctor)" />
            <button type="submit" class="nav-link text-dark"
                style="border: none; background-color: transparent; cursor: pointer;">Registration</button>
            <div class="card mb-4">
                <div class="card-header">
                    @doctor.Firstname
                </div>
                <div class="card-header">
                    @doctor.Lastname
                </div>
                <div class="card-header">
                    @doctor.MedicalDepartment
                </div>
            </div>
        </form>
    }
</div>

ClinicApp/ClinicApp.Presentation/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BonaDea</title>
    <link rel="stylesheet" href="Index.cshtml.css" asp-append-version="true">
</head>

<body>

</body>

</html>

ClinicApp/ClinicApp.Presentation/Views/Home/Login.cshtml
@model MedicalReceptionisLogintDTO;
@{
  ViewData["Title"] = "Login";
}

<span class="text-danger">@ViewData["Error"]</span>

<form method="post" asp-controller="Home" asp-action="Login">
  <div class="mb-3">
    <label class="form-label" asp-for="@Model.Email">Email</label>
    <input type="email" class="form-control" asp-for="@Model.Email">
    <span class="text-danger" asp-validation-for="@Model.Email"></span>
  </div>
  <div class="mb-3">
    <label class="form-label" asp-for="@Model.Password">Password</label>
    <input type="password" class="form-control" asp-for="@Model.Password">
    <span class="text-danger" asp-validation-for="@Model.Password"></span>
  </div>
  <button type="submit" class="btn btn-success">Save</button>
</form>



@section Scripts {
  <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
  <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

ClinicApp/ClinicApp.Presentation/Views/Patient/CreatePatient.cshtml
@model ViewModelDoctorPatient;
@{
  ViewData["Title"] = "Create Patient";
}



<form method="post" asp-controller="Registration" asp-action="RegistrationPatient">

  <input type="hidden" name="doctor.Id" value="@Model.doctor.Id" />
  <input type="hidden" name="doctor.FIN" value="@Model.doctor.FIN" />
  <input type="hidden" name="doctor.Firstname" value="@Model.doctor.Firstname" />
  <input type="hidden" name="doctor.Lastname" value="@Model.doctor.Lastname" />
  <input type="hidden" name="doctor.MedicalDepartment" value="@Model.doctor.MedicalDepartment" />

  <div class="mb-3">
    <label class="form-label" asp-for="@Model.patient.FIN">FIN</label>
    <input type="text" class="form-control" asp-for="@Model.patient.FIN">
    <span class="text-danger" asp-validation-for="@Model.patient.FIN"></span>
  </div>
  <div class="mb-3">
    <label class="form-label" asp-for="@Model.patient.Firstname">Firstname</label>
    <input type="text" class="form-control" asp-for="@Model.patient.Firstname">
    <span class="text-danger" asp-validation-for="@Model.patient.Firstname"></span>
  </div>
  <div class="mb-3">
    <label class="form-label" asp-for="@Model.patient.Lastname">Lastname</label>
    <input type="text" class="form-control" asp-for="@Model.patient.Lastname">
    <span class="text-danger" asp-validation-for="@Model.patient.Lastname"></span>
  </div>
  <div class="mb-3">
    <label class="form-label" asp-for="@Model.patient.Email">Email</label>
    <input type="email" class="form-control" asp-for="@Model.patient.Email">
    <span class="text-danger" asp-validation-for="@Model.patient.Email"></span>
  </div>

  <button type="submit" class="btn btn-success">Save</button>
</form>



@section Scripts {
  <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
  <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

ClinicApp/ClinicApp.Presentation/Views/Patient/RegistrationPatient.cshtml
@model string
@{
    ViewData["Title"] = "Registration";
}



<section class="main-content">
    <h2>Service list</h2>
    <form method="get" asp-controller="Doctor" asp-action="ShowDoctorByMedicalDepartment">
        <input type="hidden" name="medicalDepartment" value=1 />
        <input type="hidden" name="patientFIN" value="@Model" />
        <button type="submit" class="nav-link text-dark" style="border: none; background-color: transparent; cursor: pointer;">Dentistry</button>
    </form>
    <form method="get" asp-controller="Doctor" asp-action="ShowDoctorByMedicalDepartment">
        <input type="hidden" name="medicalDepartment" value=2 />
        <input type="hidden" name="patientFIN" value="@Model" />
        <button type="submit" class="nav-link text-dark" style="border: none; background-color: transparent; cursor: pointer;">Therapy</button>
    </form>
    <form method="get" asp-controller="Doctor"  asp-action=ShowDoctorByMedicalDepartment>
        <input type="hidden" name="medicalDepartment" value=3 />
        <input type="hidden" name="patientFIN" value="@Model" />
        <button type="submit" class="nav-link text-dark" style="border: none; background-color: transparent; cursor: pointer;">Surgery</button>
    </form>
</section>

ClinicApp/ClinicApp.Presentation/Views/Patient/ShowAllPatients.cshtml
@model IEnumerable<Patient>;
@{
  ViewData["Title"] = "Patient List";
}


<h2>Patients</h2>
<div>
  @foreach (var patient in Model)
  {
    <div class="card mb-4">
      <div class="card-header">
        @patient.Firstname
      </div>
      <div class="card-header">
        @patient.Lastname
      </div>
      <div class="card-header">
        @patient.Email
      </div>
    </div>
  }
</div>

ClinicApp/ClinicApp.Presentation/Views/Patient/ShowPatientsByDoctor.cshtml
@model ViewModelPatientsByDoctor;
@{
    ViewData["Title"] = "Doctor`s patients";
}

@if(Model.doctor != null && Model.patients != null){
<h2>Dr. @Model.doctor.Firstname @Model.doctor.Lastname `s patients</h2>
<div>
    @foreach (var patient in Model.patients)
    {
        <form method="get" asp-controller="Patient" asp-action="ShowPatientsByDoctor">
            <input type="hidden" name="doctor" value="@patient.FIN" />
            <div class="card mb-4">
                <div class="card-header">
                    @patient.Firstname
                </div>
                <div class="card-header">
                    @patient.Lastname
                </div>
                <div class="card-header">
                    @patient.Email
                </div>
            </div>
        </form>
    }
</div>
}

ClinicApp/ClinicApp.Presentation/Views/Shared/_Layout.cshtml
@inject IAuthorizationService authorizationService

@{
    var isAdmin = authorizationService.AuthorizeAsync(User, "Admins").Result.Succeeded;
    var isAuthenticated = User.Identity.IsAuthenticated;
}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClinicApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ClinicApp.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <h1>Welcome to BoneDea Customer relationship management</h1>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <img class="navbar-toggler-icon" src="/icon.png" alt="" />
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bonadea</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if(!isAuthenticated){
                            <li class="nav-item" >
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                            </li>
                        }
                        @if(isAdmin){
                            <li class="nav-item" >
                                <a class="nav-link text-dark" asp-area="" asp-controller="Registration"
                                    asp-action="RegistrationEmployee">Registration new employee</a>
                            </li>
                        }
                        @if(isAuthenticated){
                            <li class="nav-item" >
                                <a class="nav-link text-dark" asp-area="" asp-controller="Registration"
                                    asp-action="RegistrationPatient">Registration new patient</a>
                            </li>
                            <li class="nav-item" >
                                <a class="nav-link text-dark" asp-area="" asp-controller="Patient"
                                    asp-action="ShowAllPatients">Patients</a>
                            </li>
                            <li class="nav-item" >
                                <a class="nav-link text-dark" asp-area="" asp-controller="Doctor"
                                    asp-action="ShowAllDoctors">Doctors</a>
                            </li>
                            <li class="nav-item" >
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                    asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>



    @* <footer>
    <p>&copy; 2024 BonaDea. All rights reserved.</p>
    </footer> *@

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>